# Generated by Django 2.2.4 on 2023-10-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('poll_name', models.CharField(max_length=45, verbose_name='poll name')),
                ('updated_at', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('user_name', models.CharField(max_length=255, verbose_name='user name')),
                ('user_email', models.CharField(max_length=255, verbose_name='user email')),
                ('updated_at', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, verbose_name='date created')),
                ('vote', models.CharField(max_length=255, verbose_name='vote')),
                ('updated_at', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
    ]
